version: '3.9'

services:
  postgresql:
    image: postgres:15.4
    restart: always
    env_file:
      - .POSTGRESQL.env
    volumes:
      - ./dumps/pgsql.sql:/docker-entrypoint-initdb.d/pgsql.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
     - app-network

  mindfulguard_server:
      image: mindfulguard/server:dev
      container_name: mindfulguard_server
      restart: always
      env_file:
        - .SERVER.env
      ports:
        - 80:8080
      depends_on:
        - postgresql
      networks:
        - app-network
      working_dir: /opt/.mindfulguard
      command: ["uvicorn", "mindfulguard.__main__:app", "--host", "0.0.0.0", "--port", "8080"]
      
networks:
 app-network:
   driver: bridge

volumes:
  minio:
  pgdata: