version: '3.9'

services:
  postgresql:
    image: postgres:15.4
    restart: always
    env_file:
      - .SERVER.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

  cacheredis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .SERVER.env
    volumes:
      - cache:/data
    networks:
      - app-network

  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address ":9090"
    ports:
      - 9090:9090
      - 9000:9000
    volumes:
      - ~/.minio/data:/data
    env_file:
      - .SERVER.env
    networks:
      - app-network

  consul:
    image: hashicorp/consul:1.18
    restart: always
    container_name: consul
    command: sh -c "consul agent -server -bootstrap -client 0.0.0.0 -ui -data-dir=/consul/data & sleep 10 && consul kv import @/tmp/init-data-consul.json && tail -f /dev/null"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./data/init-data-consul.json:/tmp/init-data-consul.json
      - consul-data:/consul/data
      - consul-config:/consul/config
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  cache:
  minio:
  consul-data:
  consul-config:
