version: '3.9'

services:
  postgresql:
    image: postgres:15.4
    restart: always
    env_file:
      - .SERVER.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
     - app-network

  mindfulguard_server:
    image: server_temp:latest
    container_name: mindfulguard_server
    restart: always
    env_file:
      - .SERVER.env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - cacheredis
      - postgresql
      - minio
    networks:
      - app-network

  cacheredis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    env_file: 
      - .SERVER.env
    volumes: 
      - cache:/data
    networks:
      - app-network

  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address ":9090"
    ports:
      - 9090:9090
      - 9000:9000
    volumes:
      - ~/.minio/data:/data
    env_file:
      - .SERVER.env
    networks:
      - app-network

networks:
 app-network:
   driver: bridge

volumes:
  minio:
  pgdata:
  cache: