version: '3.9'

services:
  db:
    image: postgres:15.4
    restart: always
    env_file:
      - .env
    volumes:
      - ./dumps/pgsql.sql:/docker-entrypoint-initdb.d/pgsql.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: