[pgsql]
host="localhost"
port="5432"
database="mypass"
user="mypass"
password="12345"

[authentication]
registration=true

    [authentication.totp]
        [authentication.totp.lengths]
        reserve_codes_length = 6

    [authentication.lengths]
    token_length = 128
    login_length = 50
    secret_string_length = 512

    [authentication.public.configuration]
    password_rule = "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[\\W]).{8,64}$"
    aes_mode = "GCM"

        [authentication.public.configuration.PBKDF2]
        iterations = 10000
        sha = "sha256"

            [authentication.public.configuration.PBKDF2.lengths]
            key_length = 64

[safe]
    [safe.lengths]
    name_length = 64
    description_length = 580

[records]
    [records.categories]
    array = [
        "LOGIN",
        "PASSWORD",
        "API_CREDENTIAL",
        "SERVER",
        "DATABASE",
        "CREDIT_CARD",
        "MEMBERSHIP",
        "PASSPORT",
        "SOFTWARE_LICENSE",
        "OUTDOOR_LICENSE",
        "SECURE_NOTE",
        "WIRELESS_ROUTER",
        "BANK_ACCOUNT",
        "DRIVER_LICENSE",
        "IDENTITY",
        "REWARD_PROGRAM",
        "DOCUMENT",
        "EMAIL_ACCOUNT",
        "SOCIAL_SECURITY_NUMBER",
        "MEDICAL_RECORD",
        "SSH_KEY"
        ]
    [records.types]
    array = [
        "STRING",
        "EMAIL",
        "CONCEALED",
        "URL",
        "OTP",
        "DATE",
        "MONTH_YEAR",
        "MENU",
        "FILE"
    ]