[pgsql]
host="localhost"
port="5432"
database="mypass"
user="mypass"
password="12345"

[authentication]
registration=true
smtp="email.example.com"
blocked_domains = ["email.com","email2.com"]
token_expiration_default = 60

    [authentication.TOTP]#!add account verification using TOTP (optional) and add 2FA TOTP!

    [authentication.lengths]
    aes_length=64
    token_length = 128
    login_length = 50
    secret_string_length = 512

    [authentication.public.configuration]
    iterations = 10000
    sha_client = "sha256"
    password_rule = "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[\\W]).{8,64}$"

[safe]
    [safe.lengths]
    name_length = 256
    description_length = 500